version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - DB_HOST=34.72.232.212
      - DB_USER=estoeld
      - DB_PASS=estoeld
      - DB_DATA=estoeld
